### ISSUE TITLE
Quality of Life

### ISSUE THREAD

**Issue by 10522** [SquishedPotatoe/esgst#1]
@SquishedPotatoe сan you please add [these](https://github.com/JustArchi/ESGST#changes) features and fix these bugs:

![image](https://github.com/user-attachments/assets/943288f4-62c6-4d96-b2a2-d62ad8660327)

These custom links are not removed from the Discussions menu:

![323232323](https://github.com/user-attachments/assets/8573b1d9-3558-46bf-9c7b-b29c37fe76cc)

**Comment by SquishedPotatoe** [comment]
What feature is this red enter button related to, I have not come across this.

**Comment by SquishedPotatoe** [comment]
@10522 everything done except the filtering descriptions which i will revisit at a later date.
