### ISSUE TITLE
Old whitelist sync bug

### ISSUE THREAD

**Issue by pizzahut2** [SquishedPotatoe/esgst#2]
I'm on Firefox, I used the original extension previously. Currently I use the updated userscript.

Problem is this, when syncing a whitelist with more than one page, the last page gets updated with hearts (if you allow the [Whitelist/Blacklist Highlighter](https://www.steamgifts.com/account/settings/profile?esgst=settings&id=wbh) to run there), but they're removed on all other pages. So I don't know if I whitelisted someone until visiting their SG user profile - and toggling the heart off and on again to make ESGST recognise it.

This bug was introduced with v8.9.0. v8.8.8 was fine, which I got from [addons.mozilla.org](https://addons.mozilla.org/firefox/addon/esgst/versions/).

https://github.com/rafaelgomesxyz/esgst/issues/1739

**Comment by SquishedPotatoe** [comment]
@pizzahut2 I am not seeing this maybe it was fixed with the sync changes i did a couple of days ago. Test version 8.10.1 and let me know if it still persists.

**Comment by pizzahut2** [comment]
I have to admit that I didn't take a look at the recent commits, what a coincidence that you did those changes just a day or two before I opened an issue.

I've updated ESGST and it seems to work after I tried it a 2nd time. Maybe it needed a browser restart or saving changes.

Well done, thanks for the fix!
